import {
  ContentBlock,
  Attachment
} from './types/social-components/index.d.js';

export * from './types/social-components/index.d.js';

// export {
//   Attachment
// } from './types/social-components/index.d.js';

export type ImageboardId = '4chan' | '2ch' | '8ch' | 'kohlchan' | 'arisuchan' | 'endchan' | 'lainchan';

type ImageboardEngine = '4chan' | 'vichan' | 'OpenIB' | 'lynxchan' | 'makaba';

interface ImageboardConfigBoard {
	id: string;
	title: string;
	category?: string;
}

interface ImageboardConfigApi {
	// "Get boards list" API URL.
	// `api.getBoards` is required if there's no `boards` parameter.
	getBoards?: string;

	// "Find boards by a query" API URL.
	findBoards?: string;

	// "Get threads list" API URL template.
	getThreads: string;

	// "Get threads list including their latest comments" API URL template.
	getThreadsWithLatestComments?: string;

	// "Get threads list (first page) including their latest comments" API URL template.
	getThreadsWithLatestCommentsFirstPage?: string;

	// "Get threads list (N-th page) including their latest comments" API URL template.
	getThreadsWithLatestCommentsPage?: string;

	// "Get threads stats" API URL template.
	getThreadsStats?: string;

	// "Get thread comments" API URL template.
	getThread: string;

	// "Get archived thread comments" API URL template.
	getArchivedThread?: string;
}

export interface ImageboardConfig {
	id: string;
	domain: string;
	engine: ImageboardEngine;
	boards?: ImageboardConfigBoard[];
	api: ImageboardConfigApi;
  // A template for a board URL.
	boardUrl: string;
  // A template for a thread URL.
	threadUrl: string;
  // A template for a comment URL.
	commentUrl: string;
  // Attachment URL template.
	attachmentUrl?: string;
  // Attachment thumbnail URL pattern.
	attachmentThumbnailUrl?: string;
  // Non-picture and non-video attachment URL pattern.
  fileAttachmentUrl?: string;
  // (required by `8ch` engine (8kun.top)`)
  attachmentUrlFpath?: string;
  // (required by `8ch` engine (8kun.top)`)
  attachmentThumbnailUrlFpath?: string;
  defaultAuthorName?: string | Record<string, string>;
  // (required by `lynxchan` engine)
  thumbnailSize?: number;
}

export type HttpRequestMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface HttpRequestOptions {
	body?: string;
	headers?: Record<string, string>;
}

export type HttpRequestResult = string;

export interface HttpRequestResultWithRedirectToUrl {
	response: string;
	url: string;
}

interface Messages {
  comment?: {
    default?: string;
    deleted?: string;
    external?: string;
  };
  thread?: {
    default?: string;
  };
  // https://gitlab.com/catamphetamine/social-components/-/tree/master#messages
  textContent?: {
		block?: {
			audio?: string;
			video?: string;
			picture?: string;
			attachment?: string;
			inline?: {
				attachment?: string;
				link?: string;
				linkTo?: string;
			}
		};
  };
}

interface ImageboardOptionsOverridable {
	parseContent?: boolean;
	addParseContent?: boolean;
	commentLengthLimit?: number;
}

interface ImageboardOptions extends ImageboardOptionsOverridable {
	request: (method: HttpRequestMethod, url: string, parameters: HttpRequestParameters) => Promise<HttpRequestResult | HttpRequestResultWithRedirectToUrl>;
	commentUrl?: string;
	threadUrl?: string;
	messages?: Messages;
	useRelativeUrls?: boolean;
	expandReplies?: boolean;
	getPostLinkProperties?: (comment?: Comment) => object;
	getPostLinkText?: (postLink: object) => string?;
}

export type BoardId = string;
export type ThreadId = number;
export type CommentId = number;

export interface Board {
  id: BoardId;
  title: string;
  category?: string;
  description?: string;
  notSafeForWork?: boolean;
  bumpLimit?: number;
  commentsPerHour?: number;
  maxAttachmentsInThread?: number;
  maxCommentLength?: number;
  maxAttachmentSize?: number;
  maxVideoAttachmentSize?: number;
  maxVideoAttachmentDuration?: number;
  maxAttachmentsSize?: number;
  createThreadCooldown?: number;
  postCommentCooldown?: number;
  attachFileCooldown?: number;
  features?: {
    sage?: boolean;
    name?: boolean;
  };
}

export interface BoardBadge {
	id: string;
	title: string;
}

export interface Thread {
  id: ThreadId;
  boardId: BoardId;
  title?: string;
  autogeneratedTitle?: string;
  createdAt?: Date;
  updatedAt?: Date;
  commentsCount: number;
  attachmentsCount: number;
  commentAttachmentsCount: number;
  uniquePostersCount?: number;
  comments: Comment[];
  onTop?: boolean;
  onTopOrder?: number;
  locked?: boolean;
  trimming?: boolean;
  archived?: boolean;
  archivedAt?: Date;
  bumpLimitReached?: boolean;
  attachmentLimitReached?: boolean;
  customSpoilerId?: number;
  board?: {
    title?: string;
    bumpLimit?: number;
    maxCommentLength?: number;
    maxAttachmentsSize?: number;
    maxAttachmentSize?: number;
    maxAttachments?: number;
    features?: {
      subject?: boolean;
      attachments?: boolean;
      tags?: boolean;
      votes?: boolean;
    };
    badges?: BoardBadge[];
  }
}

export type GetCommentById = (id: CommentId) => Comment | undefined;

export type RawCommentContent = string;

// This library always returns an array of content blocks when parsing a comment's content,
// even when it's just a single "block" of simple text like `[["Text"]]`.
// That's just how `social-components-parser` works.
//
// export type ParsedCommentContent = Content;
export type ParsedCommentContent = ContentBlock[];

export interface Comment {
  id: CommentId;
  title?: string;
  createdAt: Date;
  updatedAt?: Date;

  authorIsThreadAuthor?: boolean;
  authorId?: string;
  authorIdColor?: string;
  authorNameIsId?: boolean;
  authorName?: string;
  authorEmail?: string;
  authorTripCode?: string;
  authorCountry?: string;
  authorBadgeUrl?: string;
  authorBadgeName?: string;
  authorRole?: string;
  authorRoleScope?: string;
  authorBan?: boolean;
  authorBanReason?: string;
  authorVerified?: boolean;

  sage?: boolean;
  upvotes?: number;
  downvotes?: number;
  content?: RawCommentContent | ParsedCommentContent;
  contentPreview?: ParsedCommentContent;
  inReplyTo?: number[] | Comment[];
  inReplyToRemoved?: number[];
  replies?: number[] | Comment[];
  attachments?: Attachment[];

  parseContent?: (options?: { getCommentById: GetCommentById }) => void;
  hasContentBeenParsed?: () => boolean;
  onContentChange?: (options?: { getCommentById: GetCommentById }) => void;
}

interface GetThreadsOptions extends ImageboardOptionsOverridable {
	withLatestComments?: boolean;
	maxLatestCommentsPages?: number;
	latestCommentLengthLimit?: number;
	sortByRating?: boolean;
}

interface GetThreadOptions extends ImageboardOptionsOverridable {
	archived?: boolean;
	afterCommentId?: CommentId;
	afterCommentsCount?: number;
}

export interface Imageboard {
	getBoards: () => Promise<Board[]>;
	getAllBoards: () => Promise<Board[]>;
	hasMoreBoards: () => boolean;
	findBoards: (query: string) => Promise<Board[]>;
	canSearchForBoards: () => boolean;
	getThreads: (parameters: { boardId: BoardId }, options?: GetThreadsOptions) => Promise<Thread[]>;
	getThread: (parameters: { boardId: BoardId, threadId: ThreadId }, options?: GetThreadOptions) => Promise<Thread>;
	vote: (parameters: { up: boolean, boardId: BoardId, threadId: ThreadId, commentId: CommentId }) => Promise<boolean>;
}

export function getConfig(imageboardId: ImageboardId): ImageboardConfig;

export function getCommentText(comment: Comment, options?: {
	messages?: Messages;
	skipPostQuoteBlocks?: boolean;
	skipGeneratedPostQuoteBlocks?: boolean;
}): string | undefined;

function imageboard(imageboardIdOrConfig: ImageboardId | ImageboardConfig, options: ImageboardOptions): Imageboard;

export default imageboard;