import parseThreadsPageResponse from './parseThreadsPageResponse.js'

import Chan from '../../../Chan.js'

describe('parseThreadsPageResponse', () => {
	it('should parse threads page response', () => {
		const twoCh = new Chan('2ch', {
			messages: {
				comment: {
					deleted: 'Deleted comment',
					external: 'Comment from another thread',
					default: 'Comment'
				}
			}
		})

		parseThreadsPageResponse(INPUT, {}).pageCount.should.equal(14)

		twoCh.parseThreadsPage(INPUT, { boardId: 'a', withLatestComments: true }).should.deep.equal([
			{
				id: 7658994,
				"commentsCount": 2,
				"createdAt": new Date('2023-11-03T11:26:21.000Z'),
				"locked": true,
				"updatedAt": new Date('2023-11-03T18:52:37.000Z'),
				"attachmentsCount": 2,
				"autogeneratedTitle": "Сап двач, сижу в армейке, в командосе, переодически есть мно…",
				"board": {
					"title": "Аниме",
					"attachmentsMaxTotalSize": 40960,
					"bumpLimit": 500,
					"commentContentMaxLength": 15000,
					"defaultAuthorName": "Аноним",
					"features": {
						"attachments": true,
						"badges": false,
						"commentTitle": true,
						"countryFlags": false,
						"threadTags": false,
						"threadTitle": true,
						"votes": false
				  }
				},
				"boardId": 'a',
				"commentAttachmentsCount": 1,
				comments: [
					{
						id: 7658994,
						"attachments": [
						  {
						    "picture": {
						      "height": 1280,
						      "size": 745472,
						      "sizes": [
						        {
						          "height": 250,
						          "type": "image/jpeg",
						          "url": "/a/thumb/7658994/16990107821930s.jpg",
						          "width": 250
						        }
						      ],
						      "type": "image/jpeg",
						      "url": "/a/src/7658994/16990107821930.jpg",
						      "width": 1280
						    },
						    "type": "picture"
						  }
						],
						"content": [
						  [
						    "Сап двач, сижу в армейке, в командосе, переодически есть много свободного времени, трачу его с сослуживцем на превращение в аниму дебила... Короче я большой фанат берсерка, да и в принципе я люблю какие нибудь старые анимешки чекнуть, хочу попросить подсказать ещё подобных глубоких произведений,  про средневековые замесы, мечту, дружбу, да бля похуй, короче ебал я в рот че то перечислять"
						  ]
						],
						"createdAt": new Date('2023-11-03T11:26:21.000Z')
					}
				],
				latestComments: [
					{
						id: 7658999,
						"content": [
						  [
						    {
						      "boardId": "a",
						      "content": [
						        {
						          "block": true,
						          "content": "Сап двач, сижу в армейке, в командосе, переодически есть много свободного времени, трачу его с сослуживцем на превращение в аниму дебила... Короче я большой фанат берсерка, да и в …",
						          "generated": true,
						          "type": "quote"
						        }
						      ],
						      "postId": 7658994,
						      "postIsRoot": true,
						      "threadId": 7658994,
						      "type": "post-link",
						      "url": "/a/7658994"
						    },
						    "\n",
						    "Берсерк уникальный",
						    "\n",
						    "Рубаки попробуй"
						  ]
						],
						"createdAt": new Date('2023-11-03T12:02:24.000Z'),
						"inReplyTo": [
							7658994
						]
					}
				]
			}
		])
	})
})

const INPUT = {
	"advert_bottom_image": "/banners/4gQaWQjM41r6dfy5.png",
	"advert_bottom_link": "/banners/4gQaWQjM41r6dfy5/",
	"advert_mobile_image": "/banners/RAswFRQKQQGKYy5c.png",
	"advert_mobile_link": "/banners/RAswFRQKQQGKYy5c/",
	"advert_top_image": "/banners/4gQaWQjM41r6dfy5.png",
	"advert_top_link": "/banners/4gQaWQjM41r6dfy5/",
	"board": {
		"bump_limit": 500,
		"category": "Японская культура",
		"default_name": "Аноним",
		"enable_dices": false,
		"enable_flags": false,
		"enable_icons": false,
		"enable_likes": false,
		"enable_names": true,
		"enable_oekaki": false,
		"enable_posting": true,
		"enable_sage": true,
		"enable_shield": false,
		"enable_subject": true,
		"enable_thread_tags": false,
		"enable_trips": true,
		"file_types": [
			"jpg",
			"png",
			"gif",
			"webm",
			"sticker",
			"mp4",
			"youtube",
			"webp",
			"webp",
			"webp",
			"webp",
			"webp"
		],
		"id": "a",
		"info": "Конференция доски в Телеграме - \u003ca href=\"https://telegram.me/anime2ch\"\u003e@anime2ch\u003c/a\u003e",
		"info_outer": "аниме, 2d, вайфу",
		"max_comment": 15000,
		"max_files_size": 40960,
		"max_pages": 25,
		"name": "Аниме",
		"threads_per_page": 15
	},
	"board_banner_image": "/ololo/mus_6.png",
	"board_banner_link": "mus",
	"board_speed": 4,
	"current_page": 2,
	"current_thread": 0,
	"is_board": true,
	"is_index": false,
	"pages": [
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13
	],
	"threads": [
		{
			"files_count": 2,
			"posts": [
				{
					"banned": 0,
					"board": "a",
					"closed": 1,
					"comment": "Сап двач, сижу в армейке, в командосе, переодически есть много свободного времени, трачу его с сослуживцем на превращение в аниму дебила... Короче я большой фанат берсерка, да и в принципе я люблю какие нибудь старые анимешки чекнуть, хочу попросить подсказать ещё подобных глубоких произведений,  про средневековые замесы, мечту, дружбу, да бля похуй, короче ебал я в рот че то перечислять",
					"date": "03/11/23 Птн 14:26:21",
					"email": "",
					"endless": 0,
					"files": [
						{
							"displayname": "YtHyMQ5PD8k.jpg",
							"fullname": "YtHyMQ5PD8k.jpg",
							"height": 1280,
							"md5": "5801eb151505be6d2e1710959055e634",
							"name": "16990107821930.jpg",
							"path": "/a/src/7658994/16990107821930.jpg",
							"size": 728,
							"thumbnail": "/a/thumb/7658994/16990107821930s.jpg",
							"tn_height": 250,
							"tn_width": 250,
							"type": 1,
							"width": 1280
						}
					],
					"files_count": 2,
					"lasthit": 1699037557,
					"name": "Аноним",
					"num": 7658994,
					"op": 0,
					"parent": 0,
					"posts_count": 1,
					"sticky": 0,
					"subject": "Сап двач, сижу в армейке, в командосе, переодически есть много свободного времени, трачу его с сослу",
					"tags": "",
					"timestamp": 1699010781,
					"trip": "",
					"views": 43
				},
				{
					"banned": 0,
					"board": "a",
					"closed": 0,
					"comment": "\u003ca href=\"/a/res/7658994.html#7658994\" class=\"post-reply-link\" data-thread=\"7658994\" data-num=\"7658994\"\u003e\u003e\u003e7658994 (OP)\u003c/a\u003e\u003cbr\u003eБерсерк уникальный\u003cbr\u003eРубаки попробуй",
					"date": "03/11/23 Птн 15:02:24",
					"email": "",
					"endless": 0,
					"files": null,
					"lasthit": 1699037557,
					"name": "Аноним",
					"num": 7658999,
					"op": 0,
					"parent": 7658994,
					"sticky": 0,
					"subject": "",
					"timestamp": 1699012944,
					"trip": "",
					"views": 0
				}
			],
			"posts_count": 1,
			"thread_num": 7658994
		}
	]
}