export default [
	{
		id: 204,
		"attachmentsCount": 1,
		"autogeneratedTitle": "x files marathon",
		"boardId": "x",
		"commentAttachmentsCount": 0,
		"comments": [
		  {
		    "attachments": [
		      {
		        "picture": {
		          "height": 1400,
		          "size": 206015,
		          "type": "image/jpeg",
		          "url": "/file/64c4f80bfc5d0df815933b7ca984372fdce981576d34b758a71d0b1806b38b86.jpg",
		          "width": 1400,
			        "sizes": [
			          {
			            "height": 128,
			            "type": "image/jpeg",
			            "url": "/file/thumb/64c4f80bfc5d0df815933b7ca984372fdce981576d34b758a71d0b1806b38b86.jpg",
			            "width": 128
			          }
			        ]
		        },
		        "type": "picture"
		      }
		    ],
		    "authorBan": true,
		    "authorBanReason": "Fuck off",
		    "authorName": "👻",
		    "content": [
		      [
		        "x files marathon",
		        "\n",
		        "Gay link here"
		      ]
		    ],
		    "createdAt": new Date('2023-10-26T14:32:54.674Z'),
		    "id": 204,
		    "updatedAt": new Date('2023-10-26T16:30:18.633Z')
		  }
		],
		"commentsCount": 1,
		"createdAt": new Date('2023-10-26T14:32:54.674Z')
	}
]