import generatePostQuote from 'social-components/utility/post/generatePostQuote.js'

/**
 * If `thread.title` is missing then either copy it
 * from the first comment's `title` or attempt to
 * autogenerate it from the first comment's `content`.
 * @param {object} thread
 * @param {object} [options.messages]
 * @param {number} [options.maxLength] — See `maxLength` argument of `trimText()` in `social-components`.
 * @param {number} [options.minFitFactor] — See `minFitFactor` option of `trimText()` in `social-components`.
 * @param {number} [options.maxFitFactor] — See `maxFitFactor` option of `trimText()` in `social-components`.
 * @param {boolean} [options.parseContent] — The `parseContent` option used when constructing an imageboard instance.
 */
export default function generateThreadTitle(thread, options = {}) {
	const {
		// (optional)
		// `messages: object?`
		// "Messages" ("strings", "labels") used when generating comment `content` text.
		messages,
		// (optional)
		// Maximum length of an autogenerated thread title.
		// Is `60` by default.
		maxLength,
		minFitFactor,
		maxFitFactor
	} = options
	if (!thread.title) {
		thread.autogeneratedTitle = generatePostQuote(thread.comments[0], {
			messages,
			maxLength: maxLength || 60,
			minFitFactor,
			maxFitFactor,
			stopOnNewLine: true
		})
	}
}