import getPostSummary from 'social-components/commonjs/utility/post/getPostSummary'
import { forEachFollowingQuote } from 'social-components/commonjs/utility/post/combineQuotes'

/**
 * Adds "in-reply-to" quotes.
 * Has some CPU usage.
 * @param {any} content — Comment `content`. Must be a root-level `content`.
 * @param {function} getPostById — Retuns comment by id.
 * @param {object} options
 * @param {object} contentParent — Shouldn't be passed. Is only passed internally when recursing. The parent block of `content` block.
 * @param {boolean} isLastInParagraph — If the `content` block is the last one in `contentParent`.
 * @return {boolean} [contentDidChange] — Returns `true` if `content` did change (either as a result of setting an in-reply-to quote or as a result of setting "deleted post"/"hidden post" flag).
 */
export default function setInReplyToQuotes(
	content,
	getPostById,
	options,
	contentParent,
	isFirstInParagraph = true,
	isLastInParagraph = true
) {
	if (Array.isArray(content)) {
		let i = 0
		let contentDidChange = false
		while (i < content.length) {
			const part = content[i]
			const partsCount = content.length
			if (setInReplyToQuotes(
				part,
				getPostById,
				options,
				content,
				contentParent ? (isFirstInParagraph ? i === 0 : false) : true,
				contentParent ? (isLastInParagraph && i === content.length - 1) : true
			)) {
				contentDidChange = true
			}
			// Check if some elements have been removed
			// (or maybe hypothetically added)
			// in which case adjust the cycle index.
			if (content.length !== partsCount) {
				i += content.length - partsCount
			}
			i++
		}
		return contentDidChange
	}
	// Post content can be empty.
	// Or maybe even post part's content.
	// Like `{ type: 'attachment', attachmentId: 1 }`.
	if (!content) {
		return
	}
	if (typeof content === 'string') {
		return
	}
	// Only set quotes for "standalone" `post-link`s.
	// (`post-link`s being the only content on its line)
	const index = contentParent.indexOf(content)
	const isTheOnlyOneOnLine =
		(isFirstInParagraph || contentParent[index - 1] === '\n') &&
		(isLastInParagraph || contentParent[index + 1] === '\n')
	if (!isTheOnlyOneOnLine) {
		if (content.type === 'post-link') {
			if (options && options.messages && options.messages.comment && options.messages.comment.default) {
				content.content = '(' + options.messages.comment.default.toLowerCase() + ')'
			}
		}
		return
	}
	if (content.type === 'post-link') {
		// Autogenerated parent post quotes are updated after YouTube videos have been loaded.
		// If non-autogenerated post quote for this post link has already been set then skip it.
		if (Array.isArray(content.content) && content.content[0].type === 'quote') {
			if (!content.content[0].generated) {
				return
			}
		}
		// If the quoted post has been deleted, is hidden or is from another thread.
		if (content.postWasDeleted || content.postIsHidden || content.postIsExternal) {
			// If it's the first run then transform the text content to a quote.
			if (typeof content.content === 'string') {
				content.content = [{
					type: 'quote',
					generated: true,
					content: content.content
				}]
				// Content did change.
				return true
			}
			// Otherwise, skip it.
			return
		}
		// Get the post being quoted.
		// `Array.find()` is slow for doing it every time.
		// A "postsById" index is much faster.
		const quotedPost = getPostById(content.postId)
		// This shouldn't happen because `setPostLinksContent()`
		// is supposed to be run before this function
		// that sets `postWasDeleted: true` flag for missing posts.
		if (!quotedPost) {
			console.error(`Post #${content.postId} not found`)
			return
		}
		// If the quoted post link is the last content element in the post then
		// don't perform further checks and generate the quote for the quoted post.
		if (isLastInParagraph) {
			setPostLinkQuote(content, quotedPost, options)
			return true
		}
		const quotes = []
		// See if there's already an existing post quote for this post link.
		// (composed manually by post author)
		const startFromIndex = index + 2
		const quotesCount = forEachFollowingQuote(contentParent, startFromIndex, (quote, i) => {
			// A post link quote is rendered as a hyperlink
			// and having nested hyperlinks will result in invalid HTML markup.
			// To prevent that, strip links from the quote.
			stripLinks(quote.content)
			// Separate quotes with new lines.
			if (quotes.length > 0) {
				quotes.push('\n')
			}
			quotes.push(quote)
		})
		if (quotesCount > 0) {
			content.content = quotes
			// Remove the combined quotes and "\n"s before them from post content.
			// Don't remove the "\n" after the last quote.
			contentParent.splice(index + 1, 1 + quotes.length)
		} else {
			// Autogenerate `post-link` quote text.
			setPostLinkQuote(content, quotedPost, options)
		}
		return true
	}
	// Recurse into post parts.
	return setInReplyToQuotes(
		content.content,
		getPostById,
		options,
		content,
		isFirstInParagraph,
		isLastInParagraph
	)
}

// Inline quotes can contain hyperlinks too. For example,
// `2ch.hk` autoparses links in comment text when it's submitted
// and if there's a quoted link then it will autoparse that link.
// Such nested links would result in a React warning:
// "validateDOMNesting(...): <a> cannot appear as a descendant of <a>.".
function stripLinks(content) {
	if (Array.isArray(content)) {
		let i = 0
		while (i < content.length) {
			if (typeof content[i] === 'object') {
				// Handling just a simple case here
				// and not recursing into nested arrays.
				if ((content[i].type === 'link' || content[i].type === 'post-link') &&
					typeof content[i].content === 'string') {
					content[i] = content[i].content
				}
			}
			i++
		}
	}
}

function setPostLinkQuote(postLink, post, options) {
	const text = getPostSummary(post, {
		messages: options && options.messages && options.messages.contentType,
		maxLength: 180,
		countNewLines: true,
		fitFactor: 1.35
	})
	if (text) {
		// Set `content.quote` to the quoted post text abstract.
		// Doesn't set `content.post` object to prevent JSON circular structure.
		// Compacts multiple paragraphs into multiple lines.
		postLink.content = [{
			type: 'quote',
			content: text,
			generated: true
		}]
	}
}